<?php
/**
 * @file
 * Provides hooks and helper functions.
 */
use \Drupal\ddc_scheduled_access\EntityWrapper\Node\NodeWrapper;
use \Drupal\ddc_scheduled_access\EntityWrapper\User\UserWrapper;

/**
 * Implements hook_node_grants().
 */
function ddc_scheduled_access_node_grants($account, $op) {
  $user_wrapper = new UserWrapper($account);
  return $user_wrapper->nodeGrants($op);
}

/**
 * Implements hook_node_access_records().
 */
function ddc_scheduled_access_node_access_records($node) {
  $node_wrapper = new NodeWrapper($node->nid);
  return $node_wrapper->accessRecords();
}
